website/music/urls.py
from django.conf.urls import url
from . import views                 # string view argument are deprecated

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),                                      # /music/
    url(r'^(?P<album_id>\d+)/$', views.detail, name='detail'),                  # /music/<album_id>/
    url(r'^(?P<album_id>\d+)/favorite/$', views.favorite, name='favorite'),     # /music/<album_id>/favorite/
]

website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

website/music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    # on_delete = if Album will be deleted, delete all linked Songs too.
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/music/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Album, Song


def index(request):
    all_albums = Album.objects.all()
    context = {
        'all_albums': all_albums,
    }
    return render(request, 'index.html', context)


def detail(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    return render(request, 'detail.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    error_message = ''
    try:
        selected_song = album.song_set.get(id=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        error_message = "you did not select a valid song"
        return render(request, 'detail.html', {'album': album,
                                               'error_message': error_message},)
    else:
        if not selected_song:
            selected_song.is_favorite = True
            selected_song.save()
        else:
            error_message = 'this song is already in your Favorites'
        return render(request, 'detail.html', {'album': album, 'error_message': error_message})

website/music/templates/detail.html
<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}


<form action="{% url 'music:favorite' album.id%}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}"/>
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png"/>
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

website/music/templates/index.html
{% if all_albums %}
    <h3>All my albums:</h3>
    <ul>
        {% for album in all_albums %}
            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>

{% else %}
    <h3>You don't have any albums yet</h3>
{% endif %}